services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: sqlsrv
      DB_HOST: tu-endpoint-rds.amazonaws.com
      DB_PORT: 1433
      DB_DATABASE: nombre_db
      DB_USERNAME: usuario
      DB_PASSWORD: clave
