services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: archivo_digital_laravel_app
    ports:
      - "8080:80"
    working_dir: /var/www/html
    env_file:
      - .env
